-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 13:48:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`用户主表`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`用户主表` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `账号` VARCHAR(45) NULL,
  `密码` VARCHAR(45) NULL,
  `手机` VARCHAR(45) NULL,
  `角色?` VARCHAR(45) NULL,
  `手机端token` VARCHAR(45) NULL,
  `用户类型` VARCHAR(45) NULL COMMENT '资产，资金，借款人，平台内部人员\n',
  `is_delete` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '0是删除，1是未删除',
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户主表';


-- -----------------------------------------------------
-- Table `mydb`.`bm_borrower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_borrower` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account_id` INT NULL,
  `borrower_name` VARCHAR(40) NOT NULL COMMENT '借款人名称/简称',
  `business_ownership` INT NULL COMMENT '业务归属',
  `manager_id` INT NULL COMMENT '客户经理',
  `business_source` TINYINT(2) NOT NULL COMMENT '业务来源',
  `customer_source_code` VARCHAR(45) NOT NULL COMMENT '客户来源',
  `source_unique_id` VARCHAR(100) NULL COMMENT '外部来源唯一ID',
  `recommender` VARCHAR(20) NULL COMMENT '推荐人',
  `institution` VARCHAR(40) NULL COMMENT '所属机构',
  `borrower_type` TINYINT(2) NOT NULL COMMENT '借款人类型',
  `risk_assessment` TINYINT(2) NULL COMMENT '风险评估',
  `phone` VARCHAR(20) NULL COMMENT '移动/固定电话',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BM_借款人_用户主表1_idx` (`account_id` ASC),
  CONSTRAINT `fk_BM_借款人_用户主表1`
    FOREIGN KEY (`account_id`)
    REFERENCES `mydb`.`用户主表` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_借款人信息|M';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_sshf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_sshf` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `ss_company` VARCHAR(40) NULL COMMENT '社保单位名称',
  `ss_pay_base` DECIMAL(10,5) NULL COMMENT '社保缴存基数',
  `ss_pay_stop_date` DATETIME NULL COMMENT '社保缴费截止年月',
  `hf_company` VARCHAR(40) NULL COMMENT '公积金单位名称',
  `hf_open_date` DATETIME NULL COMMENT '公积金开户日期',
  `hf_pay_stop_date` DATETIME NULL COMMENT '公积金缴费截止年月',
  `hf_month_pay` DECIMAL(14,2) NULL COMMENT '公积金月缴额',
  `hf_query_date` DATETIME NULL COMMENT '公积金查询日期',
  `hr_query_balance` DECIMAL(14,2) NULL COMMENT '公积金查询时余额',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `借款人_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `借款人`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_社保|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL COMMENT '姓名',
  `mobile_phone` VARCHAR(20) NOT NULL COMMENT '移动电话',
  `contacts_priority` TINYINT(2) NULL COMMENT '优先级',
  `relationship` VARCHAR(10) NOT NULL COMMENT '与客户关系',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1对1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `多对1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_联系人|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`common_attachment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`common_attachment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `host_id` INT NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  `file_url` VARCHAR(300) NOT NULL,
  `file_type` TINYINT(2) NOT NULL COMMENT '车辆证件,合同证件,身份证件,车辆图片',
  `file_host` VARCHAR(100) NOT NULL COMMENT '个人客户(身份证,银行卡,房产证,税单,照片),企业客户,贷款信息,车辆,\n个人住房,个人车辆,银行关联,借款明细,抵押物',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(2) NOT NULL DEFAULT 0 COMMENT '0是删除，1是未删除',
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `多对1_idx` (`host_id` ASC),
  CONSTRAINT `多对1`
    FOREIGN KEY (`host_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '附件|bm_borrower,N|lm_collateral,N|lm_loan_detail,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_income`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_income` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `personal_income_source` TINYINT(1) NULL COMMENT '个人主要收入来源',
  `personal_monthly_income` DECIMAL(14,2) NULL COMMENT '个人月收入',
  `personal_annual_income` DECIMAL(14,2) NULL COMMENT '个人年收入',
  `family_income_source` TINYINT(1) NULL COMMENT '家庭主要收入来源',
  `family_monthly_income` DECIMAL(14,2) NULL COMMENT '家庭月收入',
  `family_annual_income` DECIMAL(14,2) NULL COMMENT '家庭年收入',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_家庭收入|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_work`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_work` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `work_company_type` TINYINT(2) NULL COMMENT '单位类型',
  `position` TINYINT(2) NULL COMMENT '职务',
  `title_level` TINYINT(2) NULL COMMENT '职称级别',
  `department` VARCHAR(10) NULL COMMENT '所在单位部门',
  `induction_time` DATETIME NULL COMMENT '入职时间',
  `ss_type` TINYINT(2) NULL COMMENT '社保类型',
  `occupation` CHAR(6) NULL COMMENT '职业',
  `industry` CHAR(6) NULL COMMENT '所属行业',
  `monthly_income` DECIMAL(14,2) NULL COMMENT '单位月薪金',
  `pay_date` DATETIME NULL COMMENT '每月发薪日',
  `other_monthly_income` DECIMAL(14,2) NULL COMMENT '单位其他月均收入',
  `company_name` VARCHAR(30) NOT NULL COMMENT '工作单位',
  `company_address` VARCHAR(100) NOT NULL COMMENT '工作地址',
  `company_phone` VARCHAR(15) NOT NULL COMMENT '单位电话',
  `company_level` VARCHAR(10) NULL COMMENT '单位级别',
  `company_qualified` TINYINT(2) NULL COMMENT '单位资质',
  `company_zip_code` VARCHAR(10) NULL COMMENT '单位邮政编码',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_工作|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_base` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL COMMENT '姓名',
  `former_name` VARCHAR(20) NULL COMMENT '曾用名',
  `sex` TINYINT(1) NOT NULL COMMENT '性别',
  `birth_date` DATETIME NOT NULL COMMENT '出生年月',
  `marital_status` TINYINT(1) NOT NULL COMMENT '婚姻状况',
  `support_count` INT(2) NULL COMMENT '供养人数',
  `family_count` INT(2) NULL COMMENT '家庭人口数量',
  `education_level` TINYINT(2) NOT NULL COMMENT '教育程度',
  `mobile_phone` VARCHAR(20) NOT NULL COMMENT '移动电话',
  `telphone` VARCHAR(10) NOT NULL COMMENT '固定电话',
  `city_no` CHAR(6) NOT NULL COMMENT '城市',
  `instant_messaging` VARCHAR(10) NULL COMMENT '即时通讯',
  `current_address` VARCHAR(100) NOT NULL COMMENT '现住址',
  `shipping_address` VARCHAR(100) NOT NULL COMMENT '邮寄地址',
  `zip_code` VARCHAR(10) NULL COMMENT '邮政编码',
  `email` VARCHAR(40) NULL COMMENT '电子邮箱',
  `arrival_time` DATETIME NULL COMMENT '来居住地时间',
  `household_degister_type` TINYINT(1) NULL COMMENT '户口类型',
  `certificate_type` TINYINT(2) NOT NULL COMMENT '证件类型',
  `certificate_no` VARCHAR(40) NOT NULL COMMENT '证件号码',
  `certificate_validity_date` DATETIME NOT NULL COMMENT '证件有效期',
  `driver_license` VARCHAR(30) NOT NULL COMMENT '驾驶证',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_基本信息|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_bankflow`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_bankflow` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `bank_name` VARCHAR(50) NOT NULL COMMENT '银行名称',
  `bank_account` VARCHAR(40) NOT NULL COMMENT '银行流水账号',
  `start_date` DATETIME NOT NULL COMMENT '流水开始日期',
  `end_date` DATETIME NOT NULL COMMENT '流水结束日期',
  `balance` DECIMAL(14,2) NOT NULL COMMENT '余额',
  `is_confirm` TINYINT(1) NOT NULL COMMENT '账号是否查实',
  `assets_statistics_date` DATETIME NOT NULL COMMENT '资产统计日期',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:10`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_银行流水主表|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_bank_flow_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_bank_flow_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_bank_flow_id` INT NOT NULL COMMENT '银行流水主表ID',
  `record_date` DATETIME NOT NULL COMMENT '记录时间',
  `amount` DECIMAL(14,2) NOT NULL COMMENT '进出额',
  `balance` DECIMAL(14,2) NOT NULL COMMENT '余额',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`bm_bank_flow_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_bank_flow_id`)
    REFERENCES `mydb`.`bm_bankflow` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_银行流水记录|bm_bankflow,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_bank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `bank_code` VARCHAR(10) NULL,
  `bank_name` VARCHAR(50) NOT NULL COMMENT '银行名称',
  `bank_branch_name` VARCHAR(50) NOT NULL COMMENT '分行/开户行名称',
  `account_no` VARCHAR(40) NOT NULL COMMENT '银行账号',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_开户行|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_house` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `owner` VARCHAR(40) NOT NULL COMMENT '产权人',
  `house_type` TINYINT(2) NOT NULL COMMENT '房屋性质',
  `acreage` INT NOT NULL COMMENT '住房面积',
  `valuation` DECIMAL(14,2) NOT NULL COMMENT '估值',
  `address` VARCHAR(100) NOT NULL COMMENT '地址',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:n_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:n`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_住房|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL COMMENT '借款人id',
  `plate_number` VARCHAR(10) NOT NULL COMMENT '车牌号',
  `mileage` DECIMAL(7,2) NULL COMMENT '里程',
  `valuation` DECIMAL(14,2) NOT NULL COMMENT '估值',
  `brand` VARCHAR(10) NOT NULL COMMENT '品牌',
  `vehicle_model` VARCHAR(20) NOT NULL COMMENT '车辆型号',
  `vin_no` VARCHAR(20) NULL COMMENT '车架号',
  `service_life` VARCHAR(3) NULL COMMENT '报废年限',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:n_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:n`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_车辆|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_assets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `securities_describe` VARCHAR(200) NULL COMMENT '有价证券描述',
  `securities_value` DECIMAL(14,2) NULL COMMENT '有价证券价值',
  `other_assets` VARCHAR(200) NULL COMMENT '其他资产',
  `other_assets_value` DECIMAL(14,2) NULL COMMENT '其他资产估值',
  `bank_loan_describe` VARCHAR(200) NULL COMMENT '银行贷款描述',
  `bank_loan_amount` DECIMAL(14,2) NULL COMMENT '银行贷款金额',
  `personal_loan_describe` VARCHAR(200) NULL COMMENT '个人借款描述',
  `personal_loan_amount` DECIMAL(14,2) NULL COMMENT '个人借款金额',
  `other_liabilities_describe` VARCHAR(200) NULL COMMENT '其他负债描述',
  `other_liabilities_amount` DECIMAL(14,2) NULL COMMENT '其他负债金额',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_资产|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_credit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `credit_card_count` INT NULL COMMENT '信用卡数量',
  `credit_card_total_amount` DECIMAL(25,5) NULL COMMENT '信用卡总额度',
  `credit_card_use_ratio` DECIMAL(5,4) NULL COMMENT '信用卡使用比例',
  `credit_card_monthly_payment` DECIMAL(14,2) NULL COMMENT '信用卡月供',
  `credit_card_uncleare_uncancel_account_count` INT NULL COMMENT '信用卡未结清/未销户账户数',
  `credit_card_overdue_account_count` INT NULL COMMENT '信用卡发生过预期账户数',
  `credit_card_overdue90_account_count` INT NULL COMMENT '信用卡有过90天以上预期账户数',
  `credit_card_other_guarantee_count` INT NULL COMMENT '信用卡为他人担保笔数',
  `loan_count` INT NULL COMMENT '贷款笔数',
  `loan_total_amount` DECIMAL(25,5) NULL COMMENT '贷款总额度',
  `loan_balance` DECIMAL(14,2) NULL COMMENT '贷款余额',
  `loan_monthly_payment` DECIMAL(14,2) NULL COMMENT '贷款月供金额',
  `load_overdue_info` VARCHAR(200) NULL COMMENT '贷款逾期信息',
  `home_loan_uncleare_uncancel_account_count` INT NULL COMMENT '住房贷款未结清/未销户账户数',
  `home_loan_overdue_account_count` INT NULL COMMENT '住房贷款发生过预期账户数',
  `home_loan_overdue90_account_count` INT NULL COMMENT '住房贷款有过90天以上预期账户数',
  `home_loan_other_guarantee_count` INT NULL COMMENT '住房贷款为他人担保笔数',
  `other_loan_uncleare_uncancel_account_count` INT NULL COMMENT '其他贷款未结清/未销户账户数',
  `other_loan_overdue_account_count` INT NULL COMMENT '其他贷款发生过预期账户数',
  `other_loan_overdue90_account_count` INT NULL COMMENT '其他贷款有过90天以上预期账户数',
  `other_loan_other_guarantee_count` INT NULL COMMENT '其他贷款为他人担保笔数',
  `guarantee_count` INT NULL COMMENT '担保笔数',
  `guarantee_total_amount` DECIMAL(25,5) NULL COMMENT '担保总金额',
  `guarantee_balance` DECIMAL(14,2) NULL COMMENT '担保余额',
  `guarantee_overdue_status` TINYINT(2) NULL COMMENT '担保逾期状况',
  `credit_query_count` INT NULL COMMENT '征信查询次数',
  `one_year_query_count` INT NULL COMMENT '近一年内查询次数',
  `chinacourt_litigation_count` INT NULL COMMENT '法院网诉讼次数',
  `personal_reputation_social_position` VARCHAR(200) NULL COMMENT '个人口碑及社会地位',
  `other_credit_describe` VARCHAR(200) NULL COMMENT '其他信用描述',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_信用状况|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL COMMENT '借款人',
  `name` VARCHAR(30) NOT NULL COMMENT '名称',
  `company_type` TINYINT(2) NOT NULL COMMENT '公司性质',
  `business_license` VARCHAR(30) NULL COMMENT '营业执照号码',
  `register_capital` DECIMAL(14,2) NULL COMMENT '注册资本',
  `institution_code` VARCHAR(30) NULL COMMENT '机构代码证',
  `corporation` VARCHAR(40) NULL COMMENT '法定代表人',
  `address` VARCHAR(100) NOT NULL COMMENT '经营地址',
  `telephone` VARCHAR(20) NULL COMMENT '固定电话',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:n_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:n`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_关联企业|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_other`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_other` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `is_provide_pay_bill` TINYINT(1) NOT NULL COMMENT '是否提供工资单据',
  `is_provide_address_bill` TINYINT(1) NOT NULL COMMENT '是否提供地址相关单据',
  `is_provide_accumulation_fund_bill` TINYINT(1) NOT NULL COMMENT '是否提供公积金单据',
  `is_provide_incumbency_certificate` TINYINT(1) NOT NULL COMMENT '是否有在职证明',
  `is_have_lawsuit` TINYINT(1) NOT NULL COMMENT '是否有诉讼案件',
  `is_have_criminal_record` TINYINT(1) NOT NULL COMMENT '是否有犯罪记录',
  `credit_information` TINYINT(2) NULL COMMENT '征信情况',
  `loan_overdue_count` INT NULL COMMENT '贷款逾期次数',
  `taboo_items` VARCHAR(200) NULL COMMENT '忌讳事项',
  `faith` VARCHAR(200) NULL COMMENT '宗教信仰',
  `hobby` VARCHAR(200) NULL COMMENT '兴趣爱好',
  `character` VARCHAR(200) NULL COMMENT '性格描述',
  `health` VARCHAR(200) NULL COMMENT '健康描述',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `remark` VARCHAR(200) NULL COMMENT '其他备注',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_其他|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_additional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_additional` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `phone_service_providers` TINYINT(2) NULL COMMENT '手机运营商',
  `phone_attribution` TINYINT(5) NULL COMMENT '手机归属地',
  `phone_account_pwd` VARCHAR(40) NULL COMMENT '手机账号密码',
  `jiebei_limit` DECIMAL(14,2) NULL COMMENT '借呗额度',
  `huabei_limit` DECIMAL(14,2) NULL COMMENT '花呗额度',
  `jiedaibao_account` VARCHAR(20) NULL COMMENT '借贷宝账号',
  `zhifubao_account` VARCHAR(20) NULL COMMENT '支付宝账号',
  `zhima_credit` INT NULL COMMENT '芝麻信用分',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1:1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1:1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_附加|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_base`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_base` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL COMMENT '公司名称',
  `short_name` VARCHAR(40) NULL COMMENT '公司简称',
  `register_capital` DECIMAL(14,2) NOT NULL COMMENT '注册资本',
  `national_tax_no` VARCHAR(30) NULL COMMENT '国税登记号',
  `institution_code` VARCHAR(30) NULL COMMENT '组织机构代码证号码',
  `local_tax_no` VARCHAR(30) NULL COMMENT '地税登记号',
  `business_license` VARCHAR(30) NULL COMMENT '营业执照代码',
  `business_license_start_date` DATETIME NULL COMMENT '营业执照起始日期',
  `business_license_end_date` DATETIME NULL COMMENT '营业执照到期日期',
  `loan_card_no` VARCHAR(30) NULL COMMENT '贷款卡编号',
  `register_address` VARCHAR(100) NOT NULL COMMENT '登记地址',
  `address_detail` VARCHAR(45) NULL COMMENT '街道门牌',
  `business_scope` VARCHAR(100) NULL COMMENT '经营范围',
  `main_products_describe` VARCHAR(45) NULL COMMENT '主营产品描述',
  `staff_size` INT NULL COMMENT '成员人数',
  `office_address` VARCHAR(100) NOT NULL COMMENT '办公地址',
  `zip_address` VARCHAR(100) NULL COMMENT '邮编地址',
  `company_area_size` INT NULL COMMENT '经营场所面积',
  `company_area_owner` TINYINT(1) NULL COMMENT '经营场所所有权',
  `company_area_rent` DECIMAL(14,2) NULL COMMENT '经营场所月供',
  `corporation` VARCHAR(40) NULL COMMENT '公司法人',
  `company_phone` VARCHAR(20) NOT NULL COMMENT '公司电话',
  `city_no` CHAR(6) NULL COMMENT '城市',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_基本信息|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_executive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_executive` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `sex` TINYINT(1) NOT NULL COMMENT '性别',
  `certificate_type` TINYINT(2) NULL COMMENT '证件类型',
  `certificate_no` VARCHAR(40) NULL COMMENT '证件号码',
  `office_phone` VARCHAR(20) NOT NULL COMMENT '办公电话',
  `home_phone` VARCHAR(20) NULL COMMENT '固定电话',
  `mobile_phone` VARCHAR(20) NOT NULL COMMENT '手机电话',
  `leader_type` TINYINT(1) NULL COMMENT '领导类型',
  `position` VARCHAR(20) NOT NULL COMMENT '职位',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_高管信息|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_shareholder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_shareholder` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `shareholder_name` VARCHAR(40) NOT NULL COMMENT '股东姓名',
  `shareholder_type` TINYINT(2) NOT NULL COMMENT '股东类型',
  `certificate_type` TINYINT(2) NULL COMMENT '证件类型',
  `certificate_no` VARCHAR(40) NULL COMMENT '证件号码',
  `sharehold_ratio` DECIMAL(5,4) NOT NULL COMMENT '持股比例',
  `sharehold_amount` DECIMAL(14,2) NOT NULL COMMENT '持股金额',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_持股信息|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_channel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `channel_type` TINYINT(2) NOT NULL COMMENT '渠道类型',
  `cooperative_company` VARCHAR(40) NOT NULL COMMENT '合作单位',
  `cooperative_type` TINYINT(2) NOT NULL COMMENT '合作性质',
  `cooperative_age_limit` INT NULL COMMENT '合作年限',
  `settlement_type` TINYINT(2) NULL COMMENT '结算方式',
  `payable_account` DECIMAL(14,2) NULL COMMENT '应付账款',
  `remark` VARCHAR(200) NULL COMMENT '其他说明',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_经营渠道|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`sys_dict`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_dict` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dict_type` VARCHAR(45) NULL COMMENT '经营指标:净利润,纳税收入,销售额,采购金额,月均能耗;\n\n个人_信用状况_账户数:信用卡,住房贷款,其他贷款;\n\n税种:营业税,增值税,企业所得税,城建税,教育费附加\n\n担保信息:被担保,担保;\n\n还款计划执行方式:严格,参照\n担保方式:质押(含保证金),抵押,保证,信用,组合(含自然人保证),组合(不含自然人保证),农户联保\n\n还款方式:逐比计息,   按月还息.到期还本,到期还本付息,预收全部利息.到期还本,预收全部利息.分期还本,等额本金,等额本息,等额本金,动态利息,等本等息\n\n\n\n贷款投向:涉农,小微企业,其他\n\n\n贷款类型:信用贷,小额贷,车贷\n\n',
  `dict_type_name` VARCHAR(45) NULL COMMENT '经营指标:净利润,纳税收入,销售额,采购金额,月均能耗;\n\n个人_信用状况_账户数:信用卡,住房贷款,其他贷款;\n\n税种:营业税,增值税,企业所得税,城建税,教育费附加\n\n担保信息:被担保,担保;\n\n还款计划执行方式:严格,参照\n担保方式:质押(含保证金),抵押,保证,信用,组合(含自然人保证),组合(不含自然人保证),农户联保\n\n还款方式:逐比计息,   按月还息.到期还本,到期还本付息,预收全部利息.到期还本,预收全部利息.分期还本,等额本金,等额本息,等额本金,动态利息,等本等息\n\n\n\n贷款投向:涉农,小微企业,其他\n\n\n贷款类型:信用贷,小额贷,车贷\n\n',
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1` (`dict_type` ASC, `code` ASC))
ENGINE = InnoDB
COMMENT = '系统字典表|S';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_indicator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_indicator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `business_indicator` TINYINT(2) NOT NULL COMMENT '经营指标',
  `business_account_type` VARCHAR(45) NOT NULL COMMENT '核算方法',
  `annual_sales` DECIMAL(14,2) NULL COMMENT '年度销售额',
  `monthly_sales` DECIMAL(14,2) NULL COMMENT '月销售额',
  `annual_sales_avg` DECIMAL(14,2) NULL COMMENT '平均年度销售额',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `2_idx` (`business_indicator` ASC),
  INDEX `1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `2`
    FOREIGN KEY (`business_indicator`)
    REFERENCES `mydb`.`sys_dict` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_经营指标|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_assets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_assets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `assets_type` TINYINT(2) NOT NULL COMMENT '资产类别',
  `name` VARCHAR(40) NOT NULL COMMENT '名称',
  `value` DECIMAL(14,2) NOT NULL COMMENT '价值',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `2_idx` (`assets_type` ASC),
  INDEX `1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `2`
    FOREIGN KEY (`assets_type`)
    REFERENCES `mydb`.`sys_dict` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_资产|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_tax` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `tax_type` TINYINT(2) NOT NULL COMMENT '税种',
  `balance` DECIMAL(14,2) NOT NULL COMMENT '余额',
  `tax_date` DATETIME NOT NULL COMMENT '日期',
  `remark` VARCHAR(200) NULL COMMENT '说明',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_企业_纳税记录_借款人_企业1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_企业_纳税记录_借款人_企业1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_纳税记录|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_guarantee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_guarantee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `guarantee_category` TINYINT(2) NOT NULL COMMENT '担保类别',
  `amount` DECIMAL(14,2) NOT NULL COMMENT '金额',
  `guarantee_status` TINYINT(2) NOT NULL COMMENT '担保状态',
  `contract_no` VARCHAR(40) NOT NULL COMMENT '合同编号',
  `institution` VARCHAR(40) NULL COMMENT '金融机构',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `2_idx` (`guarantee_category` ASC),
  INDEX `fk_企业_担保信息_借款人_企业1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_企业_担保信息_借款人_企业1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `2`
    FOREIGN KEY (`guarantee_category`)
    REFERENCES `mydb`.`sys_dict` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_担保信息|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_liability`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_liability` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `borrower_name` VARCHAR(40) NOT NULL COMMENT '本负债 的负债借款人(非系统的借款人名称)',
  `bank_name` VARCHAR(50) NOT NULL COMMENT '银行',
  `amount` DECIMAL(14,2) NOT NULL COMMENT '金额',
  `balance` DECIMAL(14,2) NOT NULL COMMENT '余额',
  `start_date` DATETIME NOT NULL COMMENT '开始时间',
  `end_date` DATETIME NOT NULL COMMENT '结束时间',
  `repayment_type` TINYINT(2) NULL COMMENT '还款方式',
  `guarantee_type` TINYINT(2) NULL COMMENT '担保方式',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_企业_负债信息_借款人_企业1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_企业_负债信息_借款人_企业1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_负债信息|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_bad_debt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_bad_debt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `business_type` VARCHAR(40) NOT NULL COMMENT '未结清的不良贷款业务种类',
  `contract_no` VARCHAR(40) NOT NULL COMMENT '合同编号',
  `amount` DECIMAL(14,2) NOT NULL COMMENT '金额',
  `balance` DECIMAL(14,2) NOT NULL COMMENT '余额',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_企业_未结清的不良贷款_借款人_企业1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_企业_未结清的不良贷款_借款人_企业1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_未结清的不良贷款|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_credit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `chinacourt_litigation_count` INT NULL COMMENT '法院网诉讼次数',
  `court_excute_count` INT NULL COMMENT '人法网执行记录',
  `net_info_count` INT NULL COMMENT '互联网信息查询条数',
  `net_info_summary` VARCHAR(500) NULL COMMENT '互联网查询记录摘要',
  `reputation_social_position` VARCHAR(200) NULL COMMENT '口碑及社会地位',
  `other_credit_describe` VARCHAR(200) NULL COMMENT '其他信用描述',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_企业_信用_借款人_企业1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_企业_信用_借款人_企业1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_信用|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`bm_company_other`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_company_other` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `industry` VARCHAR(40) NOT NULL COMMENT '行业',
  `brand` VARCHAR(40) NULL COMMENT '品牌',
  `is_quoted_company` TINYINT(1) NOT NULL COMMENT '是否上市',
  `is_new_company` TINYINT(1) NOT NULL COMMENT '是否新企业',
  `is_collective_company` TINYINT(1) NOT NULL COMMENT '是否集体公司',
  `is_import_license` TINYINT(1) NOT NULL COMMENT '是否有进口经营权',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_企业_其他_借款人_企业1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_企业_其他_借款人_企业1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_企业_其他|bm_borrower,1';


-- -----------------------------------------------------
-- Table `mydb`.`lm_loan_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_loan_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `manager_id` INT NULL COMMENT '客户经理',
  `business_ownership` INT NOT NULL COMMENT '业务归属',
  `business_no` VARCHAR(20) NOT NULL COMMENT '业务编号',
  `contract_no` VARCHAR(40) NOT NULL COMMENT '合同编号',
  `business_source` TINYINT(2) NOT NULL COMMENT '业务来源',
  `loan_type` TINYINT(2) NOT NULL COMMENT '贷款类型:信用贷款,小额贷款,车贷',
  `is_need_collateral_audit` TINYINT(1) NOT NULL COMMENT '是否需要抵押品审核',
  `loan_invest` TINYINT(2) NOT NULL COMMENT '贷款投向:涉农,小微企业,其他',
  `apply_amount` DECIMAL(14,2) NOT NULL COMMENT '申请金额',
  `loan_purpose` TINYINT(2) NOT NULL COMMENT '贷款用途',
  `loan_term` DATETIME NOT NULL COMMENT '贷款期限',
  `monthly_interest_rate` DECIMAL(5,4) NOT NULL COMMENT '月利率',
  `overdue_monthly_interest_rate` DECIMAL(5,4) NOT NULL COMMENT '逾期上浮月利率',
  `penalty_monthly_interest_rate` DECIMAL(5,4) NOT NULL COMMENT '违约金月利率',
  `expected_monthly_payment` DECIMAL(14,2) NOT NULL COMMENT '期望月还款额',
  `repayment_date` DATETIME NOT NULL COMMENT '还款日',
  `apply_date` DATETIME NOT NULL COMMENT '申请日期',
  `guarantee_type` TINYINT(2) NOT NULL COMMENT '担保方式:质押(含保证金),抵押,保证,信用,组合(含自然人保证),组合(不含自然人保证),农户联保',
  `repayment_type` TINYINT(2) NOT NULL COMMENT '还款方式:逐笔计息|按月还息,到期还本|到期还本付息|预收全部利息,到期还本|预收全部利息,分期还本|等额本金|等额本息|等本等息|等额本金,动态利息',
  `repayment_execute_type` TINYINT(2) NOT NULL COMMENT '还款执行计划方式:严格,参照',
  `investment_intention` VARCHAR(45) NOT NULL COMMENT '投资意向',
  `calculation_time_type` TINYINT(2) NOT NULL COMMENT '计算时间方式:记头不记尾',
  `interest_calculation_cycle` TINYINT(2) NOT NULL COMMENT '利息计算周期:日计息,月计息',
  `repayment_calculation_type` TINYINT(2) NOT NULL COMMENT '还款日期计算策略:每周固定策略',
  `repayment_cycle` INT NOT NULL COMMENT '还款周期',
  `cycle_day_count` INT NOT NULL COMMENT '每周期天数',
  `interest_start_date` TINYINT(1) NOT NULL COMMENT '计息开始日期:发放贷款日期',
  `is_avoid_festival` TINYINT(1) NOT NULL COMMENT '还款计划是否避开节假日',
  `is_allow_advance_repayment` TINYINT(1) NOT NULL COMMENT '是否允许提前还款',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `interest_calculation_cycle`))
ENGINE = InnoDB
COMMENT = 'LM_借款明细|lm_loan_apply,1';


-- -----------------------------------------------------
-- Table `mydb`.`lm_coborrower`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_coborrower` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_detail_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `certificate_type` TINYINT(2) NOT NULL COMMENT '证件类型',
  `certificate_no` VARCHAR(40) NOT NULL COMMENT '证件号码',
  `phone` VARCHAR(20) NOT NULL,
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(2) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_共同借款人_LM_借款详细1_idx` (`lm_loan_detail_id` ASC),
  CONSTRAINT `fk_LM_共同借款人_LM_借款详细1`
    FOREIGN KEY (`lm_loan_detail_id`)
    REFERENCES `mydb`.`lm_loan_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_共同借款人|lm_loan_detail,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_cost_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_cost_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_detail_id` INT NOT NULL COMMENT '明细id',
  `billing_type` TINYINT(2) NOT NULL COMMENT '费用计费方式',
  `computational_method` TINYINT(2) NOT NULL COMMENT '计算方法',
  `collect_type` TINYINT(2) NOT NULL COMMENT '费用收取方式',
  `rate` DECIMAL(5,4) NOT NULL COMMENT '费率',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(2) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_费用信息_LM_借款详细1_idx` (`lm_loan_detail_id` ASC),
  CONSTRAINT `fk_LM_费用信息_LM_借款详细1`
    FOREIGN KEY (`lm_loan_detail_id`)
    REFERENCES `mydb`.`lm_loan_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_费用信息|lm_loan_detail,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_collateral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_collateral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_detail_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL COMMENT '名称',
  `collateral_type` TINYINT(2) NOT NULL COMMENT '抵押物类型',
  `owner_name` VARCHAR(40) NOT NULL COMMENT '产权人姓名',
  `owner_idcard_no` VARCHAR(20) NOT NULL COMMENT '产权人身份证号',
  `new_price` DECIMAL(14,2) NOT NULL COMMENT '新品价格',
  `invoice_no` VARCHAR(45) NOT NULL COMMENT '发票号码',
  `valuation` DECIMAL(14,2) NOT NULL COMMENT '估值',
  `mortgage_amount` DECIMAL(14,2) NOT NULL COMMENT '抵押金额',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_抵押物_LM_借款详细1_idx` (`lm_loan_detail_id` ASC),
  CONSTRAINT `fk_LM_抵押物_LM_借款详细1`
    FOREIGN KEY (`lm_loan_detail_id`)
    REFERENCES `mydb`.`lm_loan_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_抵押物|lm_loan_detail,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_loan_apply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_loan_apply` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `lm_loan_detail_id` INT NOT NULL,
  `customer_source_code` VARCHAR(45) NOT NULL COMMENT '客户来源',
  `source_unique_id` VARCHAR(100) NULL COMMENT '外部来源唯一ID',
  `apply_status` TINYINT(2) NOT NULL COMMENT '申请状态',
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_借款申请_LM_借款详细1_idx` (`lm_loan_detail_id` ASC),
  CONSTRAINT `fk_LM_借款申请_LM_借款详细1`
    FOREIGN KEY (`lm_loan_detail_id`)
    REFERENCES `mydb`.`lm_loan_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_借款申请|M';


-- -----------------------------------------------------
-- Table `mydb`.`lm_disbursement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_disbursement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_apply_id` INT NOT NULL COMMENT '借款申请id',
  `bm_borrower_id` INT NOT NULL COMMENT '借款人id',
  `bm_bank_id` INT NOT NULL COMMENT '开户行(发放到银行账户)',
  `lm_loan_apply_id` INT NOT NULL COMMENT '贷款编号',
  `disbursement_status` TINYINT(2) NOT NULL COMMENT '发放状态',
  `contract_no` VARCHAR(40) NOT NULL COMMENT '贷款合同编号',
  `apply_amount` DECIMAL(14,2) NOT NULL COMMENT '申请贷款金额',
  `approval_amount` DECIMAL(14,2) NOT NULL COMMENT '终审贷款金额',
  `pre_cost_amount` DECIMAL(14,2) NOT NULL COMMENT '预收费用金额;扣除本金,另收现金',
  `pre_interest` DECIMAL(14,2) NOT NULL COMMENT '扣除预收利息',
  `real_disbursement_amount` DECIMAL(14,2) NOT NULL COMMENT '实际支付金额',
  `pay_type` TINYINT(2) NOT NULL COMMENT '支付方式;三方支付平台,现金,银行转账,应收票据,债权转让',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_发放信息_bm_bank1_idx` (`bm_bank_id` ASC),
  INDEX `fk_LM_发放信息_LM_借款申请1_idx` (`lm_loan_apply_id` ASC),
  CONSTRAINT `fk_LM_发放信息_bm_bank1`
    FOREIGN KEY (`bm_bank_id`)
    REFERENCES `mydb`.`bm_bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LM_发放信息_LM_借款申请1`
    FOREIGN KEY (`lm_loan_apply_id`)
    REFERENCES `mydb`.`lm_loan_apply` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_发放记录|lm_loan_apply,1';


-- -----------------------------------------------------
-- Table `mydb`.`lm_loan_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_loan_manager` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_borrower_id` INT NOT NULL,
  `lm_loan_detail_id` INT NOT NULL,
  `lm_disbursement_id` INT NULL COMMENT '方法记录ID',
  `customer_source_code` VARCHAR(45) NOT NULL COMMENT '客户来源',
  `source_unique_id` VARCHAR(100) NULL COMMENT '外部来源唯一ID',
  `loan_status` TINYINT(2) NOT NULL COMMENT '借款状态',
  `disbursement_amount` DECIMAL(14,2) NOT NULL COMMENT '发放金额',
  `disbursement_monthly_interest_rate` DECIMAL(5,4) NOT NULL COMMENT '发放月利率',
  `disbursement_date` DATETIME NOT NULL COMMENT '发放期限',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_借款详情_bm_borrower1_idx` (`lm_borrower_id` ASC),
  INDEX `fk_LM_借款详情_LM_借款详细1_idx` (`lm_loan_detail_id` ASC),
  INDEX `fk_LM_借款详情_LM_发放信息1_idx` (`lm_disbursement_id` ASC),
  CONSTRAINT `fk_LM_借款详情_bm_borrower1`
    FOREIGN KEY (`lm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LM_借款详情_LM_借款详细1`
    FOREIGN KEY (`lm_loan_detail_id`)
    REFERENCES `mydb`.`lm_loan_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LM_借款详情_LM_发放信息1`
    FOREIGN KEY (`lm_disbursement_id`)
    REFERENCES `mydb`.`lm_disbursement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_借款详情|lm_disbursement,1';


-- -----------------------------------------------------
-- Table `mydb`.`lm_repayment_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_repayment_plan` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `lm_loan_manager_id` INT NOT NULL COMMENT '借款管理id',
  `plan_status` TINYINT(2) NOT NULL COMMENT '还款计划状态',
  `period` INT NOT NULL COMMENT '期数',
  `repayment_date` DATETIME NOT NULL COMMENT '应还日期',
  `repayment_principal` DECIMAL(14,2) NOT NULL COMMENT '应还本金',
  `repayment_interest` DECIMAL(14,2) NOT NULL COMMENT '应还利息',
  `repayment_cost` DECIMAL(14,2) NOT NULL COMMENT '应还费用',
  `repayment_total` DECIMAL(14,2) NOT NULL COMMENT '应还小计',
  `progress` VARCHAR(45) NOT NULL COMMENT '进度',
  `real_repayment_date` DATETIME NULL COMMENT '实际还款时间',
  `real_repayment_amount` DECIMAL(14,2) NULL COMMENT '当期一次还清金额',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_还款计划_LM_借款详情1_idx` (`lm_loan_manager_id` ASC),
  CONSTRAINT `fk_LM_还款计划_LM_借款详情1`
    FOREIGN KEY (`lm_loan_manager_id`)
    REFERENCES `mydb`.`lm_loan_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_还款计划|lm_loan_manager,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_overdue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_overdue` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_manager_id` INT NOT NULL,
  `lm_repayment_plan_id` INT NOT NULL,
  `overdue_day_count` INT NOT NULL COMMENT '逾期天数',
  `overdue_amount` DECIMAL(14,2) NOT NULL COMMENT '逾期金额',
  `repayment_principal` DECIMAL(14,2) NOT NULL COMMENT '实际已还款本金',
  `repayment_interest` DECIMAL(14,2) NOT NULL COMMENT '实际已还款利息',
  `repayment_cost` DECIMAL(14,2) NOT NULL COMMENT '实际已还款费用',
  `repayment_total` DECIMAL(14,2) NOT NULL COMMENT '实际已还款小计',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_逾期记录_LM_还款计划1_idx` (`lm_repayment_plan_id` ASC),
  CONSTRAINT `fk_LM_逾期记录_LM_还款计划1`
    FOREIGN KEY (`lm_repayment_plan_id`)
    REFERENCES `mydb`.`lm_repayment_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_逾期记录|lm_repayment_plan,1';


-- -----------------------------------------------------
-- Table `mydb`.`lm_bad_debt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_bad_debt` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_manager_id` INT NOT NULL,
  `bm_borrower_id` INT NOT NULL,
  `press_count` INT NOT NULL COMMENT '催收次数',
  `manager_id` INT NULL COMMENT '客户经理',
  `repayed_principal` DECIMAL(14,2) NOT NULL COMMENT '已还本金',
  `repayed_interest` DECIMAL(14,2) NOT NULL COMMENT '已还利息',
  `repayed_total` DECIMAL(14,2) NOT NULL COMMENT '已还小计',
  `unrepay_principal` DECIMAL(14,2) NOT NULL COMMENT '未还本金',
  `unrepay_interest` DECIMAL(14,2) NOT NULL COMMENT '未还利息',
  `unrepay_total` DECIMAL(14,2) NOT NULL COMMENT '未还小计',
  `unrepay_period` INT NOT NULL COMMENT '未还期数',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`lm_loan_manager_id` ASC),
  CONSTRAINT `3`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `1`
    FOREIGN KEY (`lm_loan_manager_id`)
    REFERENCES `mydb`.`lm_loan_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_坏账|lm_loan_manager,1';


-- -----------------------------------------------------
-- Table `mydb`.`社交账号表`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`社交账号表` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `社交账号类型` VARCHAR(45) NULL COMMENT 'QQ,微信,微博,..\n',
  `社交账号唯一KEY` VARCHAR(45) NULL,
  `用户主表_id` INT NOT NULL,
  `is_delete` TINYINT(2) NOT NULL DEFAULT 1 COMMENT '0是删除，1是未删除',
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_社交账号表_用户主表1_idx` (`用户主表_id` ASC),
  CONSTRAINT `fk_社交账号表_用户主表1`
    FOREIGN KEY (`用户主表_id`)
    REFERENCES `mydb`.`用户主表` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '社交账号表';


-- -----------------------------------------------------
-- Table `mydb`.`bm_personal_communication_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_personal_communication_data` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `order_id` VARCHAR(20) NULL COMMENT '订单号',
  `communication_status` TINYINT(2) NULL COMMENT '通讯数据状态',
  `order_type` TINYINT(2) NULL COMMENT '订单类型',
  `checked_phone` VARCHAR(20) NOT NULL COMMENT '被查手机号码',
  `phone_service_providers` TINYINT(1) NULL COMMENT '运营商类型',
  `access_date` DATETIME NULL COMMENT '入网时间',
  `is_real_name_auth` TINYINT(1) NULL COMMENT '实名认证',
  `auth_idcard_no` VARCHAR(30) NULL COMMENT '认证身份证号',
  `mobile_phone` VARCHAR(20) NULL COMMENT '手机号',
  `email` VARCHAR(50) NULL COMMENT '登记邮箱',
  `balance` DECIMAL(14,2) NULL COMMENT '当前余额',
  `level` INT NULL COMMENT '会员等级',
  `integral` INT NULL COMMENT '积分值',
  `net_age` INT NULL COMMENT '网龄',
  `address` VARCHAR(100) NULL COMMENT '登记地址',
  `lately_use_date` DATETIME NULL COMMENT '最近通话时间',
  `earliest_use_date` DATETIME NULL COMMENT '最早通话时间',
  `remark` VARCHAR(200) NULL COMMENT '结果备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BM_个人_通讯记录_bm_borrower1_idx` (`bm_borrower_id` ASC),
  CONSTRAINT `fk_BM_个人_通讯记录_bm_borrower1`
    FOREIGN KEY (`bm_borrower_id`)
    REFERENCES `mydb`.`bm_borrower` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_个人_通讯数据|bm_borrower,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_press_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_press_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_borrower_id` INT NOT NULL,
  `lm_loan_manager_id` INT NOT NULL,
  `press_result` TINYINT(2) NOT NULL COMMENT '催收结果',
  `press_date` DATETIME NOT NULL COMMENT '催收日期',
  `reason` VARCHAR(100) NOT NULL COMMENT '逾期缘由',
  `process` VARCHAR(45) NOT NULL COMMENT '还款进度',
  `repay_intention` VARCHAR(100) NOT NULL COMMENT '还款意向',
  `repayed_principal` DECIMAL(14,2) NOT NULL COMMENT '已还本金',
  `repayed_interest` DECIMAL(14,2) NOT NULL COMMENT '已还利息',
  `repayed_total` DECIMAL(14,2) NOT NULL COMMENT '已还小计',
  `unrepay_principal` DECIMAL(14,2) NOT NULL COMMENT '未还本金',
  `unrepay_interest` DECIMAL(14,2) NOT NULL COMMENT '未还利息',
  `unrepay_total` DECIMAL(14,2) NOT NULL COMMENT '未还小计',
  `unrepay_period` INT NOT NULL COMMENT '未还期数',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `1_idx` (`lm_loan_manager_id` ASC),
  CONSTRAINT `1`
    FOREIGN KEY (`lm_loan_manager_id`)
    REFERENCES `mydb`.`lm_loan_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_催收记录|lm_loan_manager,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_repayment_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_repayment_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_loan_manager_id` INT NOT NULL,
  `bm_borrower_id` INT NOT NULL,
  `lm_repayment_plan_id` INT NOT NULL,
  `record_status` TINYINT(2) NOT NULL COMMENT '还款记录状态',
  `repayment_date` DATETIME NOT NULL COMMENT '实际还款时间',
  `repayment_principal` DECIMAL(14,2) NOT NULL COMMENT '实际还款本金',
  `repayment_interest` DECIMAL(14,2) NOT NULL COMMENT '实际还款利息',
  `repayment_cost` DECIMAL(14,2) NOT NULL COMMENT '实际还款费用',
  `repayment_total` DECIMAL(14,2) NOT NULL COMMENT '实际还款小计',
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_还款记录_LM_借款详情1_idx` (`lm_loan_manager_id` ASC),
  INDEX `fk_LM_还款记录_LM_还款计划1_idx` (`lm_repayment_plan_id` ASC),
  CONSTRAINT `fk_LM_还款记录_LM_借款详情1`
    FOREIGN KEY (`lm_loan_manager_id`)
    REFERENCES `mydb`.`lm_loan_manager` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LM_还款记录_LM_还款计划1`
    FOREIGN KEY (`lm_repayment_plan_id`)
    REFERENCES `mydb`.`lm_repayment_plan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_还款记录|lm_repayment_plan,N';


-- -----------------------------------------------------
-- Table `mydb`.`bm_call_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bm_call_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bm_communication_data_id` INT NOT NULL,
  `phone_no` VARCHAR(20) NOT NULL COMMENT '电话号码',
  `duration` INT NOT NULL COMMENT '时长',
  `active_count` INT NOT NULL COMMENT '主叫次数',
  `called_count` INT NOT NULL COMMENT '被叫次数',
  `phone_attribution` TINYINT(5) NOT NULL COMMENT '归属地',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BM_通话记录_BM_个人_通讯数据1_idx` (`bm_communication_data_id` ASC),
  CONSTRAINT `fk_BM_通话记录_BM_个人_通讯数据1`
    FOREIGN KEY (`bm_communication_data_id`)
    REFERENCES `mydb`.`bm_personal_communication_data` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'BM_通话记录分析|bm_personal_communication_data,N';


-- -----------------------------------------------------
-- Table `mydb`.`lm_car_archives`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_car_archives` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_collateral_id` INT NOT NULL COMMENT '抵押物ID',
  `order_id` VARCHAR(20) NULL COMMENT '订单号',
  `plate_number` VARCHAR(10) NOT NULL COMMENT '车辆号码/牌照',
  `owner` VARCHAR(20) NULL COMMENT '机动车所有人',
  `idcard_no` VARCHAR(30) NULL COMMENT '身份证号码',
  `brand_cn` VARCHAR(20) NULL COMMENT '中文品牌',
  `vehicle_model` VARCHAR(20) NULL COMMENT '车辆型号',
  `vehicle_identification_code` VARCHAR(45) NULL COMMENT '车辆识别代号',
  `engine_number` VARCHAR(45) NULL COMMENT '发动机号',
  `use_type` TINYINT(2) NULL COMMENT '使用性质',
  `registration_authority` VARCHAR(45) NULL COMMENT '登记机关',
  `car_color` VARCHAR(20) NULL COMMENT '车身颜色',
  `passenger_count` INT NULL COMMENT '核定载客',
  `driver_license_code` VARCHAR(30) NULL COMMENT '行驶证芯编码',
  `initial_registration_date` DATETIME NULL COMMENT '初次登记日期',
  `registration_date` DATETIME NULL COMMENT '出厂登记日期',
  `scrap_date` DATETIME NULL COMMENT '强制报废期止',
  `insurance_validity_date` DATETIME NULL COMMENT '保险有效期止',
  `verify_validity_date` DATETIME NULL COMMENT '校验有效期止',
  `is_new_energy` TINYINT(1) NULL COMMENT '新能源汽车',
  `power` VARCHAR(10) NULL COMMENT '排量功率',
  `car_status` TINYINT(2) NULL COMMENT '机动车状态',
  `accident_escape` INT NULL COMMENT '事故逃逸',
  `vehicle_deck` VARCHAR(45) NULL COMMENT '车辆套牌',
  `vehicle_robbery` VARCHAR(45) NULL COMMENT '车辆盗抢',
  `mortgage_sign` VARCHAR(45) NULL COMMENT '抵押标记',
  `mortgage_time` DATETIME NULL COMMENT '抵押时间',
  `mortgage_holder` VARCHAR(20) NULL COMMENT '抵押权人',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_车辆档案_LM_抵押物1_idx` (`lm_collateral_id` ASC),
  CONSTRAINT `fk_LM_车辆档案_LM_抵押物1`
    FOREIGN KEY (`lm_collateral_id`)
    REFERENCES `mydb`.`lm_collateral` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_车辆档案|lm_collateral,1';


-- -----------------------------------------------------
-- Table `mydb`.`lm_car_insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lm_car_insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lm_collateral_id` INT NOT NULL COMMENT '抵押物ID',
  `brand` VARCHAR(10) NOT NULL COMMENT '车辆品牌',
  `order_id` VARCHAR(20) NULL COMMENT '订单号',
  `vin_no` VARCHAR(20) NULL COMMENT '车架号',
  `report_create_date` DATETIME NULL COMMENT '报告生成时间',
  `claim_settlement_summary` VARCHAR(500) NULL COMMENT 'summary出现理赔摘要',
  `remark` VARCHAR(200) NULL,
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_LM_车辆保险_LM_抵押物1_idx` (`lm_collateral_id` ASC),
  CONSTRAINT `fk_LM_车辆保险_LM_抵押物1`
    FOREIGN KEY (`lm_collateral_id`)
    REFERENCES `mydb`.`lm_collateral` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'LM_车辆保险|lm_collateral,N';


-- -----------------------------------------------------
-- Table `mydb`.`sys_synchronization_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sys_synchronization_info` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `raw_uuid` VARCHAR(32) NULL,
  `customer_source` TINYINT(2) NOT NULL COMMENT '客户来源',
  `source_unique_id` VARCHAR(100) NULL COMMENT '外部来源唯一标识',
  `synchronization_date` DATETIME NOT NULL,
  `synchronization_data` TEXT NOT NULL COMMENT '外部数据',
  `synchronization_result` TINYINT(2) NOT NULL COMMENT '同步结果',
  `remote_ip` VARCHAR(45) NOT NULL,
  `remark` VARCHAR(200) NULL COMMENT '备注',
  `status` TINYINT(2) NOT NULL DEFAULT 0,
  `is_delete` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` DATETIME NOT NULL,
  `create_user_id` INT NOT NULL,
  `update_time` DATETIME NOT NULL,
  `update_user_id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '系统同步表|M';


-- -----------------------------------------------------
-- Table `mydb`.`abutment_customer_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abutment_customer_info` (
  `id` INT NOT NULL,
  `appKey` VARCHAR(45) NULL,
  `customer_code` VARCHAR(45) NULL,
  `customer_name` VARCHAR(45) NULL,
  `publickey` VARCHAR(4000) NULL,
  `privatekey` VARCHAR(4000) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `company_code_UNIQUE` (`customer_code` ASC))
ENGINE = InnoDB
COMMENT = '对接商|M';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
